name: linter
on: push
jobs:
    my-job:
        runs-on: ubuntu-latest
        steps:
            - name: run linter
            run: pip install poetry
            run: poetry run flake8 hexlet_git

