name: my-linter

on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install python
        uses: actions/setup-python@v2
        with:
              python-version: 3.9
#      - name: install deps
      - name: install deps
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry add --dev flake8
          poetry run flake8 hexlet_git
