# This is a basic workflow to help you get started with Actions

name: my-linter

on: push
jobs:
  poetry-install:
    runs-on: ubuntu-latest
    steps:
      - name: install-poetry
        run: pip install poetry
                    
  my-linter:
    runs-on: ubuntu-latest
    needs: [poetry-install]
    
    steps:
      - name: make lint
        run: poetry run flake8 hexlet_git
          
